- src/licenses/mit.ts
The currently used MIT license URL references the old PHP-file based license at
http://opensource.org/licenses/mit-license.php and uses the HTTP scheme.
It got replaced with the canonical URL (https://opensource.org/licenses/MIT).
> Use canonical MIT license URL

- src/extension.ts
Previously, it'd fall back to AL instead.
> Fix typo in license switch for AGPLv3 license

- src/licenses/gplv2.ts
- src/licenses/gplv3.ts
There's two spaces before author name in GPL licenses.
```
/**
* Copyright (C) 2017  Kok Sam.
*
* This file is part of Project.
*
* Project is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* Project is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Project.  If not, see <http://www.gnu.org/licenses/>.
*
*/
```
> Remove multiple spaces before author name in GPL licenses

- src/notation.ts
I wasn't entirely sure about the multiline decorator as I've seen people use `-- `, `    ` and `` before, but I put it as ` ` because python & ruby use that and 🤷‍♂️ consistency.
> Add Lua support

- README.md
- package.json
- src/notation.ts
for the D programming language it actually shall be "/* */" instead of "/** */", because otherwise it would become part of the imbedded documentation. and that shouldnt be the default behaviour. see:  https://dlang.org/spec/ddoc.html#lexical
> add support for the D programming language

- README.md
- package-lock.json
- package.json
- src/notation.ts
Support for Julia, Crystal, Nim and Nimble has been added in the same patch, since they use basically the same rules for comments.
Except for Julia, all the languages have single line comments, using hash as token.
Tests are passing and headers work as expected
> Support has been added for Julia, Crystal, Nim and Nimble

- README.md
- src/extension.ts
- src/licenses/ccby40.ts
- src/licenses/ccbync40.ts
- src/licenses/ccbyncnd40.ts
- src/licenses/ccbyncsa40.ts
- src/licenses/ccbynd40.ts
- src/licenses/ccbysa40.ts
- src/licenses/gplv2.ts
- src/licenses/gplv3.ts
- src/notation.ts
This matches the behaviour for single line comments by removing trailing spaces from ornaments and applying them in `multiLineCommentHeader`
> Always indent multi-line comments by one space

- src/extension.ts
It got removed by the merge in f92a08e6f9ba6044f395834dd81260c7a9a61129
> Add missing space to multiLineCommentHeader

- package.json
This extension is not a linter.
> Remove Linter category from the manifest.

- src/notation.ts
GN:
Meta-build system used by Chromium, Fuchsia, Skia, and other Google-originating projects.
https://gn.googlesource.com/gn/+/master/
Starlark:
Python-subset conveniently used as a configuration language. Used in bazel.
https://github.com/bazelbuild/starlark
> Add support for gn and starlark

- package.json
- src/extension.ts
Intended to close #32 
- Adds new command, only visible in context menu of folders in explorer.
- Recursively adds license headers to all files within a directory/subdirectories
- Only inserts license header into files which do not contain one already
I tried my best to do this in a similar way to the original _insert function, but was unable to find a good way to go about it.  This currently uses the fs module to insert licenses.  This may be an inefficient way of accomplishing this task, so I can attempt to do it in a way that has similar behavior to _insert if desired, although it may be a bit uglier.
> Implements multiple file license header insertion

- package.json
in file: package.json
add an missing entry for the "Boost Software License 1.0" (BSL-1.0)
> package.json - fix: missing property for BSL1

- package.json
This is an attempt to fix #66.
As I do not have the necessary tools in my machine, it is hard for me to test whether it was actually fixed..
> Use "objectpascal" as an alias for Pascal.

- README.md
- package.json
- src/extension.ts
- src/licenses/custom.ts
Adds 2 new settings:
1. customTermsAndConditionsFile: Path to a file containing a user-defined custom terms and conditions. Overrides Custom Terms And Conditions when present.
2. customHeaderFile: Path to a file containing a user-defined custom header. Overrides Custom Header when present.
This allows users to put a custom header and/or terms and conditions in a file of their choice, instead of trying to fit it all into a single-line setting. I think this makes custom licenses easier to use and also mitigates #77
> implements customHeaderFile and customTermsAndConditionsFile

- src/licenses/agplv3.ts
The [original AGPL-v3 license](https://www.gnu.org/licenses/agpl-3.0.html) makes use single-quotes that were all replaced by double-quotes in vsc-licenser's.  
Not sure why, but I fixed this just in case :)
> Replace unwanted double-quotes in AGPL-v3 license with single-quotes

- src/extension.ts
The original method to add license to multiple files does not respect shebang in shell script or PHP file.
And the FILE field in custom license will incorrectly filled with the current file opened in the editor.
This pull request attempts to fix this two issues.
> Make multiple file mode respects shebang and outputs file names correctly.

- package.json
- src/extension.ts
- src/licenses/zlib.ts
Changes
* Added the activate event to force initialization of extension when vscode starts (fixes #98).
* Added the 'insert licenses into all files' command (fixes #84)
* Fixed the uri.parse that throwing an exception `Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//") `
> Set onStartupFinished activate event to initialize extension on startup

- src/extension.ts
A change introduced in dfbce5e1796eeefa782235f7c8e1cb2de58401d9 broke how the extension reads the author's name, always defaulting to the computer user name. This PR reverts this change.
> Fix reading the author from configuration.

- src/notation.ts
Allow svelte and vue files to have comments inserted in them as per html format
> fix: svelte and vue templates follow html really

- src/extension.ts
Ignore undefined elements that onDidChangeActiveTextEditor can (and is
documented to) send to licenser. This cleans up a lot of noise in
vscode's `Log (Window)` but doesn't change licenser's behavior since
licenser would crash on the `e.document.fileName` later in the code.
> ignore undefined in onDidChangeActiveTextEditor

- README.md
- package.json
- src/extension.ts
Hello first of all thank you for your great extension!
This PR adds the possibility for users to exclude certain file extensions. Sometimes when working on projects you can be working with files where the licenses don't make much sense. Therefor it can be a nice feature to have to possibility to disable the automatic header insertion for them only. As for now you only have two options: Delete the header every time or disable the auto insertion. And of course this is completely optional so current behavior isn't changed.
I hope you consider my addition.
> Feature: Exlude files based on their extension
