ymotongpoo/vsc-licenser

src/licenses/gplv3.ts
The file contains the wrong license number. The recommended license header according to [FSF](http://gplv3.fsf.org/wiki/index.php/Howto) should be version 3 or later for GPL version 3.
=> Changed license header to GPL version 3 instead of 2.

src/extension.ts
=> fix mplv2 license check

README.md, package.json, src/extension.ts, src/licenses/custom.ts
I'm lazy, so I'm submitting somewhat unreleated changes in a single pull request. The last two commits are related, but the first one stands on it's own. See commit messages for details.
=> Custom headers and other changes

.vscode/tasks.json, README.md, package.json, src/notation.ts
And replaced a deprecated construct in `tasks.json`.
=> Added support for the Pascal programming language.

README.md, package.json, src/extension.ts
Reslove #41.
I have no experience with typescript and vscode extension development.  Hope to get your review.
=> Add config to disable auto-insertion of header.

README.md, package.json, src/extension.ts, src/licenses/wtfpl.ts
I noticed some folks frequently use [WTFPL](http://www.wtfpl.net/about/) and it wasn't in the list of licenses.
=> Adds WTFPL

src/licenses/custom.ts
=> fix: replace all placeholder instances

src/extension.ts
=> Replace for..in of array

README.md, package.json, src/notation.ts
This change adds Elixir to the list of supported languages.
=> Add Elixir support

package.json, src/extension.ts
Created a new license type `choose` that, if selected, aloows the user to select the desired license type from a list. Demo of the final result:
**IMPORTANT:** Since I don't really know typescript or any typescript/vscode best practices, I tried to do the simplest thing that works. Feedback will be appreciated.
=> Feature: Choose a license type when creating a new file

CHANGELOG.md, README.md, package.json, src/extension.ts, src/licenses/unl.ts
=> Add support for The Unlicense.

src/notation.ts
=> Add support for LaTeX and Dart.

.vscode/tasks.json, CHANGELOG.md, README.md, package-lock.json, package.json, src/notation.ts
* upgraded depending package versions and TypeScript version
* fix error in merged commits
* updated README to reflect recent updates
=> update for 1.4.0

src/notation.ts
To insert correct comments (`/* */` instead of `//` which break on build)
=> Map postcss to css

src/extension.ts
=> Ignore files and dirs that name starts with dot.

package-lock.json, package.json, src/extension.ts
Fixes #114.
This PR removes all `save` calls from the extension's source code, and also removed and replaced some deprecated function calls.
=> Do not save after an operation.

README.md, package.json, src/extension.ts, src/licenses/busl1_1.ts
Add BUSL - 1.1 as specified by Maria DB . 
https://spdx.org/licenses/BUSL-1.1.html
=> fix: add BUSL-1.1

src/extension.ts
=> FilenameFix

src/notation.ts
This PR adds support for SQL to this extension.
Although the change is so trivial, it would be really useful for those who often write SQL like me.
=> Add support for SQL

package.json, src/extension.ts, src/licenses/eupl12.ts
This PR adds the EUPL-1.2 to this extension. I've matched the code style of the extension to the best of my ability.
=> Add EUPL-1.2.

README.md, src/notation.ts
=> Add cmake support

src/licenses/custom.ts
=> Trim CustomHeaders
